CREATE DATABASE LibraryManagement
GO
USE LibraryManagement
GO
CREATE TABLE TypeOfBook(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TypeName NVARCHAR(50) NULL
)
GO

CREATE TABLE Author(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	AuthorName NVARCHAR(50) NULL
)
GO

CREATE TABLE Publisher(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	PublisherName NVARCHAR(50) NULL,
	Address NVARCHAR(50) NULL,
	PhoneNumber NVARCHAR(11) NULL
)
GO

CREATE TABLE Book(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TypeID INT NOT NULL,
	AuthorID INT NOT NULL,
	PublisherID INT NOT NULL,
	DateIn DATETIME NULL,
	Condition NVARCHAR(30) NULL,
	Status NVARCHAR(30) NULL
	CONSTRAINT FK_TypeID FOREIGN KEY(TypeID) REFERENCES TypeOfBook(Id),
	CONSTRAINT FK_AuthorID FOREIGN KEY(AuthorID) REFERENCES Author(Id)
)
GO

CREATE TABLE Member(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	MemberName NVARCHAR(50) NULL,
	Birthday DATETIME NULL,
	Gender NVARCHAR(10) NULL,
	PhoneNumber NVARCHAR(11) NULL,
	Rank NVARCHAR(30) NULL
)
GO

CREATE TABLE Account(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	MemberID INT NOT NULL,
	AccountName NVARCHAR(30) NULL,
	Password NVARCHAR(30) NULL,
	CONSTRAINT FK_MemberID FOREIGN KEY(MemberID) REFERENCES Member(Id)
)
GO

CREATE TABLE Borrow_Return(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	BorrowDate DATETIME NULL,
	ReturnDate DATETIME NULL,
	NumberOfBooks INT NULL,
)
GO

CREATE TABLE Borrow_ReturnInfo(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Borrow_ReturnID INT NOT NULL,
	BookID INT NOT NULL,
	MemberID INT NOT NULL,
	CONSTRAINT FK_BookID FOREIGN KEY(BookID) REFERENCES Book(Id),
	CONSTRAINT FK_Member_ID FOREIGN KEY(MemberID) REFERENCES Member(Id)
)
GO